/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_app;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author RociodelosAngeles
 */
public class Consultas extends javax.swing.JInternalFrame {
Connection_MySQL cm = new Connection_MySQL();
       Connection cn= cm.get_Connection();
        ArrayList<String> Mat_Cod = new ArrayList<String>();
         DefaultListModel model = new DefaultListModel();
    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        
         try {
            
            Statement st;
            ResultSet rs;
            st = (Statement) cn.createStatement();
            String s = "select * from materias";
            rs = st.executeQuery(s);
            while (rs.next()) {        
            Mat_Cod.add(rs.getString(1));
                
            JCB_MAt.addItem(rs.getString(2));
                
                
            }                
                
                
            
        } catch (Exception e) {
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_ES = new javax.swing.JList<>();
        JCB_MAt = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Estudiantes Matriculados En Materias ");

        JL_ES.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_ES);

        JCB_MAt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        JCB_MAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_MAtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(JCB_MAt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JCB_MAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCB_MAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_MAtActionPerformed
        
         try {
            model.clear();
            Statement st;
            ResultSet rs;
            st = (Statement) cn.createStatement();
            String s = "SELECT * FROM estudiante inner join materias_has_estudiante \n" +
"on estudiante.Cedula = materias_has_estudiante.Estudiante_Cedula\n" +
"where Materias_Codigo = \'"+  Mat_Cod.get(JCB_MAt.getSelectedIndex()) +"\';";
            rs = st.executeQuery(s);
            while (rs.next()) {  
                
            model.addElement(rs.getString(2) + rs.getString(4));
                
                
            }                
                JL_ES.setModel(model);
                
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_JCB_MAtActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_MAt;
    private javax.swing.JList<String> JL_ES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
