/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_app;

import com.mysql.jdbc.Connection;


import com.mysql.jdbc.Statement;
import java.sql.ResultSet;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author RociodelosAngeles
 */
public class Est_Materias extends javax.swing.JInternalFrame {
 Connection_MySQL cm = new Connection_MySQL();
       Connection cn= cm.get_Connection();
       DefaultListModel model = new DefaultListModel();
          DefaultListModel model2 = new DefaultListModel();
            ArrayList<String> Mat_Cod = new ArrayList<String>();
            Statement st;
            ResultSet rs;
    /**
     * Creates new form Est_Materias
     */
    public Est_Materias() {
        initComponents();
        try {
            
            com.mysql.jdbc.Statement st;
            ResultSet rs;
            st = (com.mysql.jdbc.Statement) cn.createStatement();
            String s = "select * from materias";
            rs = st.executeQuery(s);
            while (rs.next()) {        
            Mat_Cod.add(rs.getString(1));
                
            JCB_MAt.addItem(rs.getString(2));
                
                
            }                
                
                
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JCB_MAt = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_ES = new javax.swing.JList<>();
        JLabel_Cont_M = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Estudiantes Matriculados En Materias ");

        JCB_MAt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        JCB_MAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_MAtActionPerformed(evt);
            }
        });

        JL_ES.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_ES);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(JCB_MAt, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLabel_Cont_M, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JCB_MAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLabel_Cont_M, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCB_MAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_MAtActionPerformed

        try {
            model.clear();
            
            st = (Statement) cn.createStatement();
            String s = "SELECT * FROM estudiante inner join materias_has_estudiante \n" +
            "on estudiante.Cedula = materias_has_estudiante.Estudiante_Cedula\n" +
            "where Materias_Codigo = \'"+  Mat_Cod.get(JCB_MAt.getSelectedIndex()) +"\';";
            rs = st.executeQuery(s);
            while (rs.next()) {

                model.addElement(rs.getString(2) + rs.getString(4));

            }
            JL_ES.setModel(model);

        } catch (Exception e) {
        }

    }//GEN-LAST:event_JCB_MAtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JCB_MAt;
    private javax.swing.JList<String> JL_ES;
    private javax.swing.JLabel JLabel_Cont_M;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
