/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_app;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Container;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author RociodelosAngeles
 */
public class Gui_Pre_Mat extends javax.swing.JInternalFrame {

    /**
     * Creates new form Gui_Pre_Mat
     */
    public Gui_Pre_Mat() {
        initComponents();
        
    
    }
    Connection_MySQL con2 = new Connection_MySQL();
    Connection con= con2.get_Connection();
    Statement st;
    ResultSet rs;
    String Nombre="";
    String NM_M1 ="1";
    String NM_M2 ="1";
    String NM_M3 ="1";
    String NM_M4 ="1";
    String NM_M5 ="1";
    String NM_M6 ="1";
    String NM_M7 ="1";
    String M1="N/A";
    String M2="N/A";
    String M3="N/A";
    String M4="N/A";
    String M5="N/A";
    String M6="N/A";
    String M7="N/A";
    ArrayList<String> Mat_Cod = new ArrayList<String>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JT_Cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JB_Search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JCB_M1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JCB_M2 = new javax.swing.JComboBox<>();
        JCB_M3 = new javax.swing.JComboBox<>();
        JCB_M4 = new javax.swing.JComboBox<>();
        JCB_M5 = new javax.swing.JComboBox<>();
        JCB_M6 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        JCB_M7 = new javax.swing.JComboBox<>();
        JRB_M1_1 = new javax.swing.JRadioButton();
        JRB_M1_2 = new javax.swing.JRadioButton();
        JRB_M1_3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        JRB_M2_1 = new javax.swing.JRadioButton();
        JRB_M2_2 = new javax.swing.JRadioButton();
        JRB_M2_3 = new javax.swing.JRadioButton();
        JRB_M3_1 = new javax.swing.JRadioButton();
        JRB_M3_2 = new javax.swing.JRadioButton();
        JRB_M3_3 = new javax.swing.JRadioButton();
        JRB_M4_1 = new javax.swing.JRadioButton();
        JRB_M4_2 = new javax.swing.JRadioButton();
        JRB_M4_3 = new javax.swing.JRadioButton();
        JRB_M5_1 = new javax.swing.JRadioButton();
        JRB_M5_2 = new javax.swing.JRadioButton();
        JRB_M5_3 = new javax.swing.JRadioButton();
        JRB_M6_1 = new javax.swing.JRadioButton();
        JRB_M6_2 = new javax.swing.JRadioButton();
        JRB_M6_3 = new javax.swing.JRadioButton();
        JRB_M7_1 = new javax.swing.JRadioButton();
        JRB_M7_2 = new javax.swing.JRadioButton();
        JRB_M7_3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        JT_Name_Display = new javax.swing.JLabel();
        JB_Save = new javax.swing.JToggleButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pre-Matricula CIERCOM");
        setAlignmentX(256.0F);
        setAlignmentY(256.0F);

        jLabel2.setText("Ingrese Su Cedula:");

        JB_Search.setText("Consular");
        JB_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SearchActionPerformed(evt);
            }
        });

        jLabel3.setText("Por Favor Seleccione Las Materias en las que usted espera poder matricularse le proximo semestre ");

        JCB_M1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        jLabel4.setText("Materia 1");

        jLabel5.setText("Materia 2 ");

        jLabel6.setText("Materia 3");

        jLabel7.setText("Materia 4");

        jLabel8.setText("Materia 5");

        jLabel9.setText("Materia 6");

        JCB_M2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        JCB_M3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        JCB_M4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        JCB_M5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        JCB_M6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jLabel10.setText("Materia 7");

        JCB_M7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));

        JRB_M1_1.setSelected(true);
        JRB_M1_1.setText("1");
        JRB_M1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M1_1ActionPerformed(evt);
            }
        });

        JRB_M1_2.setText("2");
        JRB_M1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M1_2ActionPerformed(evt);
            }
        });

        JRB_M1_3.setText("3");
        JRB_M1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M1_3ActionPerformed(evt);
            }
        });

        jLabel11.setText("# Matrícula");

        JRB_M2_1.setSelected(true);
        JRB_M2_1.setText("1");
        JRB_M2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M2_1ActionPerformed(evt);
            }
        });

        JRB_M2_2.setText("2");
        JRB_M2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M2_2ActionPerformed(evt);
            }
        });

        JRB_M2_3.setText("3");
        JRB_M2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M2_3ActionPerformed(evt);
            }
        });

        JRB_M3_1.setSelected(true);
        JRB_M3_1.setText("1");
        JRB_M3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M3_1ActionPerformed(evt);
            }
        });

        JRB_M3_2.setText("2");
        JRB_M3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M3_2ActionPerformed(evt);
            }
        });

        JRB_M3_3.setText("3");
        JRB_M3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M3_3ActionPerformed(evt);
            }
        });

        JRB_M4_1.setSelected(true);
        JRB_M4_1.setText("1");
        JRB_M4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M4_1ActionPerformed(evt);
            }
        });

        JRB_M4_2.setText("2");
        JRB_M4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M4_2ActionPerformed(evt);
            }
        });

        JRB_M4_3.setText("3");
        JRB_M4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M4_3ActionPerformed(evt);
            }
        });

        JRB_M5_1.setSelected(true);
        JRB_M5_1.setText("1");
        JRB_M5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M5_1ActionPerformed(evt);
            }
        });

        JRB_M5_2.setText("2");
        JRB_M5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M5_2ActionPerformed(evt);
            }
        });

        JRB_M5_3.setText("3");
        JRB_M5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M5_3ActionPerformed(evt);
            }
        });

        JRB_M6_1.setSelected(true);
        JRB_M6_1.setText("1");
        JRB_M6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M6_1ActionPerformed(evt);
            }
        });

        JRB_M6_2.setText("2");
        JRB_M6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M6_2ActionPerformed(evt);
            }
        });

        JRB_M6_3.setText("3");
        JRB_M6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M6_3ActionPerformed(evt);
            }
        });

        JRB_M7_1.setSelected(true);
        JRB_M7_1.setText("1");
        JRB_M7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M7_1ActionPerformed(evt);
            }
        });

        JRB_M7_2.setText("2");
        JRB_M7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M7_2ActionPerformed(evt);
            }
        });

        JRB_M7_3.setText("3");
        JRB_M7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_M7_3ActionPerformed(evt);
            }
        });

        jLabel12.setText("Estudiante");

        JT_Name_Display.setText("Nombre Estudiante");

        JB_Save.setText("Guardar");
        JB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(JB_Save)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JT_Name_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(JCB_M2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCB_M1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M7_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M7_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M7_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M6_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M6_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M6_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M5_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M5_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M5_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M4_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M4_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M4_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M3_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M3_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M3_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M2_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M2_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M2_3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JRB_M1_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(JRB_M1_2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(JRB_M1_3))))))
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JB_Search))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JT_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(JB_Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JT_Name_Display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_M1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JRB_M1_1)
                    .addComponent(JRB_M1_2)
                    .addComponent(JRB_M1_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JCB_M2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M2_1)
                    .addComponent(JRB_M2_2)
                    .addComponent(JRB_M2_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JCB_M3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M3_1)
                    .addComponent(JRB_M3_2)
                    .addComponent(JRB_M3_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JCB_M4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M4_1)
                    .addComponent(JRB_M4_2)
                    .addComponent(JRB_M4_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(JCB_M5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M5_1)
                    .addComponent(JRB_M5_2)
                    .addComponent(JRB_M5_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JCB_M6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M6_1)
                    .addComponent(JRB_M6_2)
                    .addComponent(JRB_M6_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JCB_M7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JRB_M7_1)
                    .addComponent(JRB_M7_2)
                    .addComponent(JRB_M7_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JB_Save)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SearchActionPerformed
// Pregunta si ya esta        
try {
           
                       

            st = (Statement) con.createStatement();
            
            String s = "Select Estado_Matricula from estudiante where Cedula= \'"+JT_Cedula.getText()+"\';";
            
            rs = st.executeQuery(s);
            String Stado="";
            while (rs.next()) {        
               
                Stado=rs.getString(1);
                System.out.println(Stado);
                
            }
           
            
            if (Stado.equalsIgnoreCase("1")) {
                 JOptionPane.showMessageDialog(this, "Estidiante Ya Matriculad@!");
    } else {
                JOptionPane.showMessageDialog(this, "Estidiante Por  Matricular!");
    }
        } catch (Exception e) {
            System.out.println(e);
        }


    


// TODO add your handling code here:
        try {
            
                       

            st = (Statement) con.createStatement();
            String s = "select * from estudiante Where Cedula = "+JT_Cedula.getText();
            rs = st.executeQuery(s);
             while (rs.next()) {        
               
                JT_Name_Display.setText(rs.getString(2)+" "+rs.getString(3));
                Nombre= rs.getString(2)+" "+rs.getString(2);
            }
        } catch (Exception e) {
            
        }
        
        try {
            
                       
            int cont =0;
            st = (Statement) con.createStatement();
            String s = "select * from materias";
            rs = st.executeQuery(s);
             while (rs.next()) {        
                Mat_Cod.add(rs.getString(1));
                 System.out.println(Mat_Cod.get(cont));
                 cont++;
                JCB_M1.addItem(rs.getString(2));
                JCB_M2.addItem(rs.getString(2));
                JCB_M3.addItem(rs.getString(2));
                JCB_M4.addItem(rs.getString(2));
                JCB_M5.addItem(rs.getString(2));
                JCB_M6.addItem(rs.getString(2));
                JCB_M7.addItem(rs.getString(2));
                
                
            }
        } catch (Exception e) {
        }
        
       
        
        
        
        
        
    }//GEN-LAST:event_JB_SearchActionPerformed

    private void JRB_M1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M1_1ActionPerformed

        if (JRB_M1_1.isSelected() == true) {
            JRB_M1_2.setSelected(false);
            JRB_M1_3.setSelected(false);
            NM_M1 = "1";
        }

    }//GEN-LAST:event_JRB_M1_1ActionPerformed

    private void JRB_M1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M1_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M1_2.isSelected() == true) {
            JRB_M1_1.setSelected(false);
            JRB_M1_3.setSelected(false);
            NM_M1 = "2";
        }

    }//GEN-LAST:event_JRB_M1_2ActionPerformed

    private void JRB_M1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M1_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M1_3.isSelected() == true) {
            JRB_M1_2.setSelected(false);
            JRB_M1_1.setSelected(false);
            NM_M1 = "3";

        }
    }//GEN-LAST:event_JRB_M1_3ActionPerformed

    private void JRB_M2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M2_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M2_1.isSelected() == true) {
            JRB_M2_2.setSelected(false);
            JRB_M2_3.setSelected(false);
            NM_M2 = "1";

        }

    }//GEN-LAST:event_JRB_M2_1ActionPerformed

    private void JRB_M2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M2_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M2_2.isSelected() == true) {
            JRB_M2_1.setSelected(false);
            JRB_M2_3.setSelected(false);
            NM_M2 = "2";
        }
    }//GEN-LAST:event_JRB_M2_2ActionPerformed

    private void JRB_M2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M2_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M2_3.isSelected() == true) {
            JRB_M2_2.setSelected(false);
            JRB_M2_1.setSelected(false);
            NM_M2 = "3";

        }
    }//GEN-LAST:event_JRB_M2_3ActionPerformed

    private void JRB_M3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M3_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M3_1.isSelected() == true) {
            JRB_M3_2.setSelected(false);
            JRB_M3_3.setSelected(false);
            NM_M3 = "1";

        }
    }//GEN-LAST:event_JRB_M3_1ActionPerformed

    private void JRB_M3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M3_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M3_2.isSelected() == true) {
            JRB_M3_1.setSelected(false);
            JRB_M3_3.setSelected(false);
            NM_M3 = "2";

        }
    }//GEN-LAST:event_JRB_M3_2ActionPerformed

    private void JRB_M3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M3_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M3_3.isSelected() == true) {
            JRB_M3_2.setSelected(false);
            JRB_M3_1.setSelected(false);
            NM_M3 = "3";

        }
    }//GEN-LAST:event_JRB_M3_3ActionPerformed

    private void JRB_M4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M4_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M4_1.isSelected() == true) {
            JRB_M4_2.setSelected(false);
            JRB_M4_3.setSelected(false);
            NM_M4 = "1";

        }
    }//GEN-LAST:event_JRB_M4_1ActionPerformed

    private void JRB_M4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M4_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M4_2.isSelected() == true) {
            JRB_M4_1.setSelected(false);
            JRB_M4_3.setSelected(false);
            NM_M4 = "2";

        }
    }//GEN-LAST:event_JRB_M4_2ActionPerformed

    private void JRB_M4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M4_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M4_3.isSelected() == true) {
            JRB_M4_2.setSelected(false);
            JRB_M4_1.setSelected(false);
            NM_M4 = "3";

        }
    }//GEN-LAST:event_JRB_M4_3ActionPerformed

    private void JRB_M5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M5_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M5_1.isSelected() == true) {
            JRB_M5_2.setSelected(false);
            JRB_M5_3.setSelected(false);
            NM_M5 = "1";

        }
    }//GEN-LAST:event_JRB_M5_1ActionPerformed

    private void JRB_M5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M5_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M5_2.isSelected() == true) {
            JRB_M5_1.setSelected(false);
            JRB_M5_3.setSelected(false);
            NM_M5 = "2";

        }
    }//GEN-LAST:event_JRB_M5_2ActionPerformed

    private void JRB_M5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M5_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M5_3.isSelected() == true) {
            JRB_M5_2.setSelected(false);
            JRB_M5_1.setSelected(false);
            NM_M5 = "3";
        }
    }//GEN-LAST:event_JRB_M5_3ActionPerformed

    private void JRB_M6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M6_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M6_1.isSelected() == true) {
            JRB_M6_2.setSelected(false);
            JRB_M6_3.setSelected(false);
            NM_M6 = "1";
        }
    }//GEN-LAST:event_JRB_M6_1ActionPerformed

    private void JRB_M6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M6_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M6_2.isSelected() == true) {
            JRB_M6_1.setSelected(false);
            JRB_M6_3.setSelected(false);
            NM_M6 = "2";
        }
    }//GEN-LAST:event_JRB_M6_2ActionPerformed

    private void JRB_M6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M6_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M6_3.isSelected() == true) {
            JRB_M6_2.setSelected(false);
            JRB_M6_1.setSelected(false);
            NM_M6 = "3";
        }
    }//GEN-LAST:event_JRB_M6_3ActionPerformed

    private void JRB_M7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M7_1ActionPerformed
        // TODO add your handling code here:
        if (JRB_M7_1.isSelected() == true) {
            JRB_M7_2.setSelected(false);
            JRB_M7_3.setSelected(false);
            NM_M7 = "1";
        }
    }//GEN-LAST:event_JRB_M7_1ActionPerformed

    private void JRB_M7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M7_2ActionPerformed
        // TODO add your handling code here:
        if (JRB_M7_2.isSelected() == true) {
            JRB_M7_1.setSelected(false);
            JRB_M7_3.setSelected(false);
            NM_M7 = "2";
        }
    }//GEN-LAST:event_JRB_M7_2ActionPerformed

    private void JRB_M7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_M7_3ActionPerformed
        // TODO add your handling code here:
        if (JRB_M7_3.isSelected() == true) {
            JRB_M7_2.setSelected(false);
            JRB_M7_1.setSelected(false);
            NM_M7 = "3";
        }
    }//GEN-LAST:event_JRB_M7_3ActionPerformed

    private void JB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_SaveActionPerformed
        // TODO add your handling code here:
      String Periodo="";  
      String Matricula="";
        try {
            
            
            //Obtener el Periodo Academico Activo
            
            
            
             st = (Statement) con.createStatement();
            
            String s = "Select Codigo from periodo_académico where Estado= '1';";
            
            rs = st.executeQuery(s);
            
            while (rs.next()) {        
               
                Periodo=rs.getString(1);
                System.out.println(Periodo);
                
            }
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            //Ingreso datos
                    st = (Statement) con.createStatement();
            
            String m = "INSERT INTO matricula (Estudiante , Periodo_Academico) values (?,?);";
            PreparedStatement pst = con.prepareStatement(m,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, JT_Cedula.getText());
           pst.setString(2,Periodo);
          
           int ra = pst.executeUpdate();
           
           
           // Leer Matricula Creada 
           
           st = (Statement) con.createStatement();
            
            String y = "Select idMatricula from matricula where Estudiante= \'"+JT_Cedula.getText()+"\';";
            
            rs = st.executeQuery(y);
            
            while (rs.next()) {        
               
                Matricula=rs.getString(1);
                System.out.println(Matricula);
                
            }
           
           
           
                 
           
           
           
           
           
           
           
           

        } catch (Exception e) {
        }
        
        
        
        
        // Materia 1 
        
        String M_COd = Mat_Cod.get(JCB_M1.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {

                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula,Codigo_Matricula,periodo_académico_Código) values (?,?,?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M1));
           pst.setString(4, Matricula);
           pst.setString(5, Periodo);
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 2 
        
        String M_COd2 = Mat_Cod.get(JCB_M2.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
            
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd2);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M2));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 1 
        
        String M_COd3 = Mat_Cod.get(JCB_M3.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
            
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd3);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M3));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 1 
        
        String M_COd4 = Mat_Cod.get(JCB_M4.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
            
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd4);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M4));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 1 
        
        String M_COd5 = Mat_Cod.get(JCB_M5.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
            
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd5);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M5));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 1 
        
        String M_COd6 = Mat_Cod.get(JCB_M6.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
           
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd6);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M6));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Materia 1 
        
        String M_COd7 = Mat_Cod.get(JCB_M7.getSelectedIndex());
        System.out.println(M_COd);
        
        
        try {
           
                       

            st = (Statement) con.createStatement();
            
            String s = "INSERT INTO materias_has_estudiante (Materias_Codigo , Estudiante_Cedula, N_Matricula) values (?,?,?);";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setString(1, M_COd7);
           pst.setString(2, JT_Cedula.getText());
           pst.setInt(3, Integer.valueOf(NM_M7));
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        // Cambio Esta Matricula
        
        try {
            
                       

            st = (Statement) con.createStatement();
            
            String s = "UPDATE estudiante SET Estado_Matricula =? WHERE Cedula=\'"+JT_Cedula.getText()+"\';";
            PreparedStatement pst = con.prepareStatement(s,Statement.RETURN_GENERATED_KEYS);
           pst.setBoolean(1, true);
           
           int ra = pst.executeUpdate();
           
            
            
        } catch (Exception e) {
            
        }
        
        dispose();
        JOptionPane.showMessageDialog(this, "Estidiante Matriculad@! \n "
                + "Estudiante: "+ JT_Cedula.getText()+"\n"
                        + "Nombre: "+Nombre+"\n"
                                 + "Matricula #"+ Matricula+"\n"+
                                  "Periodo: "+Periodo
                                + "Materias:\n \n"
                                + JCB_M1.getItemAt(JCB_M1.getSelectedIndex()) + "\n"
                                        + JCB_M2.getItemAt(JCB_M2.getSelectedIndex()) + "\n"
                                        + JCB_M3.getItemAt(JCB_M3.getSelectedIndex()) + "\n"
                                        + JCB_M4.getItemAt(JCB_M4.getSelectedIndex()) + "\n"
                                        + JCB_M5.getItemAt(JCB_M5.getSelectedIndex()) + "\n"
                                        + JCB_M6.getItemAt(JCB_M6.getSelectedIndex()) + "\n"
                                        + JCB_M7.getItemAt(JCB_M7.getSelectedIndex())+ "\n \n Cualquier Inconveniente Con La matrícula \nFavor Comunicarse En Secretaria Para Solicitar Cambio");
        
    }//GEN-LAST:event_JB_SaveActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton JB_Save;
    private javax.swing.JButton JB_Search;
    private javax.swing.JComboBox<String> JCB_M1;
    private javax.swing.JComboBox<String> JCB_M2;
    private javax.swing.JComboBox<String> JCB_M3;
    private javax.swing.JComboBox<String> JCB_M4;
    private javax.swing.JComboBox<String> JCB_M5;
    private javax.swing.JComboBox<String> JCB_M6;
    private javax.swing.JComboBox<String> JCB_M7;
    private javax.swing.JRadioButton JRB_M1_1;
    private javax.swing.JRadioButton JRB_M1_2;
    private javax.swing.JRadioButton JRB_M1_3;
    private javax.swing.JRadioButton JRB_M2_1;
    private javax.swing.JRadioButton JRB_M2_2;
    private javax.swing.JRadioButton JRB_M2_3;
    private javax.swing.JRadioButton JRB_M3_1;
    private javax.swing.JRadioButton JRB_M3_2;
    private javax.swing.JRadioButton JRB_M3_3;
    private javax.swing.JRadioButton JRB_M4_1;
    private javax.swing.JRadioButton JRB_M4_2;
    private javax.swing.JRadioButton JRB_M4_3;
    private javax.swing.JRadioButton JRB_M5_1;
    private javax.swing.JRadioButton JRB_M5_2;
    private javax.swing.JRadioButton JRB_M5_3;
    private javax.swing.JRadioButton JRB_M6_1;
    private javax.swing.JRadioButton JRB_M6_2;
    private javax.swing.JRadioButton JRB_M6_3;
    private javax.swing.JRadioButton JRB_M7_1;
    private javax.swing.JRadioButton JRB_M7_2;
    private javax.swing.JRadioButton JRB_M7_3;
    private javax.swing.JTextField JT_Cedula;
    private javax.swing.JLabel JT_Name_Display;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
