/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_app;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author RociodelosAngeles
 */
public class Mat_Gen_Total extends javax.swing.JInternalFrame {
 Connection_MySQL cm = new Connection_MySQL();
       Connection cn= cm.get_Connection();
 DefaultListModel model = new DefaultListModel();
          DefaultListModel model2 = new DefaultListModel();
          ArrayList<String> Mat_Cod = new ArrayList<String>();
          ArrayList<String> Mat_Num = new ArrayList<String>();
          ArrayList<String> Todo = new ArrayList<String>();
            Statement st;
            ResultSet rs;
            Statement st2;
            ResultSet rs2;
            int cnt=0;
            int cntt=0;
    /**
     * Creates new form Mat_Gen_Total
     */
    public Mat_Gen_Total() {
        initComponents();
        /// Ontiene Las aterias
        cnt=0;
        try {
            //init
            com.mysql.jdbc.Statement st;
            
            st = (com.mysql.jdbc.Statement) cn.createStatement();
            String s = "select * from materias";
            rs = st.executeQuery(s);
             while (rs.next()) {        
                 Mat_Cod.add(rs.getString(1));
            // Pbtenermos Cuantos Por materia
        try {
            
            com.mysql.jdbc.Statement st2;
            
            st2 = (com.mysql.jdbc.Statement) cn.createStatement();
            System.out.println(rs.getString(1));
            String s2 = "select * from materias_has_estudiante where Materias_Codigo = \'"+rs.getString(1)+"\';";
            rs2 = st2.executeQuery(s2);
            cnt=0;
            while (rs2.next()) {        
                System.err.println(cnt);
                cnt++;
            
            }  
            
        }
        catch ( Exception e ){
            
        }
           cntt+=cnt;
            model.addElement(rs.getString(2)+" \t\t"+String.valueOf(cnt));
            JL_General.setModel(model);
            JLTotal.setText(String.valueOf(cntt));
        

//end
            
           
            
           
           
                
                
            }  
            JL_General.setModel(model);
        }
        catch ( Exception e ){
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JL_General = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        JLTotal = new javax.swing.JLabel();

        jLabel1.setText("Resumen General De Matriculados");

        JL_General.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JL_General);

        jLabel2.setText("Total");

        JLTotal.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)
                        .addComponent(JLTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JLTotal))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLTotal;
    private javax.swing.JList<String> JL_General;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
