/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mysql_app;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;

/**
 *
 * @author RociodelosAngeles
 */
public class Resumen extends javax.swing.JInternalFrame {
     Connection_MySQL cm = new Connection_MySQL();
       Connection cn= cm.get_Connection();
    Statement st;
    ResultSet rs;
    String Periodo="";
    /**
     * Creates new form Resumen
     */
    public Resumen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        JTCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JL_Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JL_MAt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LJ_Periodo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JList_M = new javax.swing.JList<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Resumen de Matricula");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Cedula:");

        JTCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTCedulaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        JL_Name.setText("N. Estudiante");

        jLabel4.setText("# Matricula:");

        JL_MAt.setText("# Mat");

        jLabel6.setText("Periodo:");

        LJ_Periodo.setText("Periodo Académico");

        JList_M.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JList_M);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTCedula)
                                    .addComponent(JL_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JL_MAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LJ_Periodo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(JTCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JL_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JL_MAt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LJ_Periodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JTCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTCedulaActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel model = new DefaultListModel();
        model.clear();
        
        try {
            
            //obtener Ciclo Academico ACtivo 
            st = (Statement) cn.createStatement();
            
            String s = "Select Codigo from periodo_académico where Estado= '1';";
            
            rs = st.executeQuery(s);
            
            while (rs.next()) {        
               
                Periodo=rs.getString(1);
                System.out.println(Periodo);
                LJ_Periodo.setText(Periodo);
            }
            
            // Obtener Materias
            st = (Statement) cn.createStatement();
            String se = "SELECT Nombre FROM materias inner join materias_has_estudiante on materias.Codigo = materias_has_estudiante.Materias_Codigo where Estudiante_Cedula = \'"+ JTCedula.getText() +"\';";
            rs = st.executeQuery(se);
           
            while (rs.next()) {        
                System.out.println(rs.getString(1));
                model.addElement(rs.getString(1));
                
                
                
            }
            JList_M.setModel(model);
            
            // obteniendo el nombre
            
            st = (Statement) cn.createStatement();
            String s2 = "select * from estudiante where Cedula = \'"+JTCedula.getText()+"\';";
            rs = st.executeQuery(s2);
            
            while (rs.next()) {        
               
                System.out.println(rs.getString(2)+rs.getString(3));
                JL_Name.setText(rs.getString(2)+ " "+rs.getString(3));
              
                
            }
            // obtener el codigo de matricula 
            
            st = (Statement) cn.createStatement();
            String s3 = "SELECT idMatricula FROM ciercom_pre_matricula.matricula where Estudiante = \'"+JTCedula.getText()+"\';";
            rs = st.executeQuery(s3);
            
            while (rs.next()) {        
               
                System.out.println(rs.getString(1));
                JL_MAt.setText(rs.getString(1));
              
                
            }
            
            
            
        } catch (Exception e) {
        }
        
        
        
    }//GEN-LAST:event_JTCedulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_MAt;
    private javax.swing.JLabel JL_Name;
    private javax.swing.JList<String> JList_M;
    private javax.swing.JTextField JTCedula;
    private javax.swing.JLabel LJ_Periodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
